// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/interfaces.go
//
// Generated by this command:
//
//	mockgen -source internal/service/interfaces.go -destination internal/service/mocks/mock_interfaces.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "backend/internal/models"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockDurableRepo is a mock of DurableRepo interface.
type MockDurableRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDurableRepoMockRecorder
	isgomock struct{}
}

// MockDurableRepoMockRecorder is the mock recorder for MockDurableRepo.
type MockDurableRepoMockRecorder struct {
	mock *MockDurableRepo
}

// NewMockDurableRepo creates a new mock instance.
func NewMockDurableRepo(ctrl *gomock.Controller) *MockDurableRepo {
	mock := &MockDurableRepo{ctrl: ctrl}
	mock.recorder = &MockDurableRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDurableRepo) EXPECT() *MockDurableRepoMockRecorder {
	return m.recorder
}

// ClaimStockDecrements mocks base method.
func (m *MockDurableRepo) ClaimStockDecrements(ctx context.Context, now, leaseUntil time.Time, limit int) ([]models.StockDecrement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimStockDecrements", ctx, now, leaseUntil, limit)
	ret0, _ := ret[0].([]models.StockDecrement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimStockDecrements indicates an expected call of ClaimStockDecrements.
func (mr *MockDurableRepoMockRecorder) ClaimStockDecrements(ctx, now, leaseUntil, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimStockDecrements", reflect.TypeOf((*MockDurableRepo)(nil).ClaimStockDecrements), ctx, now, leaseUntil, limit)
}

// CountMembershipsByStatus mocks base method.
func (m *MockDurableRepo) CountMembershipsByStatus(ctx context.Context, productID string) (map[models.MembershipStatus]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMembershipsByStatus", ctx, productID)
	ret0, _ := ret[0].(map[models.MembershipStatus]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMembershipsByStatus indicates an expected call of CountMembershipsByStatus.
func (mr *MockDurableRepoMockRecorder) CountMembershipsByStatus(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMembershipsByStatus", reflect.TypeOf((*MockDurableRepo)(nil).CountMembershipsByStatus), ctx, productID)
}

// ExpireRightAndUpsertMembershipTx mocks base method.
func (m *MockDurableRepo) ExpireRightAndUpsertMembershipTx(ctx context.Context, token string, membership *models.QueueMembership) (*models.Right, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireRightAndUpsertMembershipTx", ctx, token, membership)
	ret0, _ := ret[0].(*models.Right)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ExpireRightAndUpsertMembershipTx indicates an expected call of ExpireRightAndUpsertMembershipTx.
func (mr *MockDurableRepoMockRecorder) ExpireRightAndUpsertMembershipTx(ctx, token, membership any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireRightAndUpsertMembershipTx", reflect.TypeOf((*MockDurableRepo)(nil).ExpireRightAndUpsertMembershipTx), ctx, token, membership)
}

// ExpireRights mocks base method.
func (m *MockDurableRepo) ExpireRights(ctx context.Context, tokens []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireRights", ctx, tokens)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExpireRights indicates an expected call of ExpireRights.
func (mr *MockDurableRepoMockRecorder) ExpireRights(ctx, tokens any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireRights", reflect.TypeOf((*MockDurableRepo)(nil).ExpireRights), ctx, tokens)
}

// GetRightByToken mocks base method.
func (m *MockDurableRepo) GetRightByToken(ctx context.Context, token string) (*models.Right, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRightByToken", ctx, token)
	ret0, _ := ret[0].(*models.Right)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRightByToken indicates an expected call of GetRightByToken.
func (mr *MockDurableRepoMockRecorder) GetRightByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRightByToken", reflect.TypeOf((*MockDurableRepo)(nil).GetRightByToken), ctx, token)
}

// IssueRightAndUpsertMembershipTx mocks base method.
func (m *MockDurableRepo) IssueRightAndUpsertMembershipTx(ctx context.Context, right *models.Right, membership *models.QueueMembership) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueRightAndUpsertMembershipTx", ctx, right, membership)
	ret0, _ := ret[0].(error)
	return ret0
}

// IssueRightAndUpsertMembershipTx indicates an expected call of IssueRightAndUpsertMembershipTx.
func (mr *MockDurableRepoMockRecorder) IssueRightAndUpsertMembershipTx(ctx, right, membership any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueRightAndUpsertMembershipTx", reflect.TypeOf((*MockDurableRepo)(nil).IssueRightAndUpsertMembershipTx), ctx, right, membership)
}

// ListMembershipsByUser mocks base method.
func (m *MockDurableRepo) ListMembershipsByUser(ctx context.Context, userID string) ([]*models.QueueMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembershipsByUser", ctx, userID)
	ret0, _ := ret[0].([]*models.QueueMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembershipsByUser indicates an expected call of ListMembershipsByUser.
func (mr *MockDurableRepoMockRecorder) ListMembershipsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembershipsByUser", reflect.TypeOf((*MockDurableRepo)(nil).ListMembershipsByUser), ctx, userID)
}

// LoadRecoverySnapshot mocks base method.
func (m *MockDurableRepo) LoadRecoverySnapshot(ctx context.Context) (*models.RecoverySnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadRecoverySnapshot", ctx)
	ret0, _ := ret[0].(*models.RecoverySnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadRecoverySnapshot indicates an expected call of LoadRecoverySnapshot.
func (mr *MockDurableRepoMockRecorder) LoadRecoverySnapshot(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadRecoverySnapshot", reflect.TypeOf((*MockDurableRepo)(nil).LoadRecoverySnapshot), ctx)
}

// MarkStockDecrementDelivered mocks base method.
func (m *MockDurableRepo) MarkStockDecrementDelivered(ctx context.Context, eventID string, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkStockDecrementDelivered", ctx, eventID, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkStockDecrementDelivered indicates an expected call of MarkStockDecrementDelivered.
func (mr *MockDurableRepoMockRecorder) MarkStockDecrementDelivered(ctx, eventID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkStockDecrementDelivered", reflect.TypeOf((*MockDurableRepo)(nil).MarkStockDecrementDelivered), ctx, eventID, now)
}

// RescheduleStockDecrement mocks base method.
func (m *MockDurableRepo) RescheduleStockDecrement(ctx context.Context, eventID string, nextAttemptAt time.Time, lastError string, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RescheduleStockDecrement", ctx, eventID, nextAttemptAt, lastError, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// RescheduleStockDecrement indicates an expected call of RescheduleStockDecrement.
func (mr *MockDurableRepoMockRecorder) RescheduleStockDecrement(ctx, eventID, nextAttemptAt, lastError, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RescheduleStockDecrement", reflect.TypeOf((*MockDurableRepo)(nil).RescheduleStockDecrement), ctx, eventID, nextAttemptAt, lastError, now)
}

// SaveInitialStock mocks base method.
func (m *MockDurableRepo) SaveInitialStock(ctx context.Context, stock *models.ProductStock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveInitialStock", ctx, stock)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveInitialStock indicates an expected call of SaveInitialStock.
func (mr *MockDurableRepoMockRecorder) SaveInitialStock(ctx, stock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveInitialStock", reflect.TypeOf((*MockDurableRepo)(nil).SaveInitialStock), ctx, stock)
}

// SaveRight mocks base method.
func (m *MockDurableRepo) SaveRight(ctx context.Context, right *models.Right) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRight", ctx, right)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRight indicates an expected call of SaveRight.
func (mr *MockDurableRepoMockRecorder) SaveRight(ctx, right any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRight", reflect.TypeOf((*MockDurableRepo)(nil).SaveRight), ctx, right)
}

// UpsertMembership mocks base method.
func (m *MockDurableRepo) UpsertMembership(ctx context.Context, membership *models.QueueMembership) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertMembership", ctx, membership)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertMembership indicates an expected call of UpsertMembership.
func (mr *MockDurableRepoMockRecorder) UpsertMembership(ctx, membership any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertMembership", reflect.TypeOf((*MockDurableRepo)(nil).UpsertMembership), ctx, membership)
}

// UseRightTx mocks base method.
func (m *MockDurableRepo) UseRightTx(ctx context.Context, token, orderID string, now time.Time) (*models.Right, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UseRightTx", ctx, token, orderID, now)
	ret0, _ := ret[0].(*models.Right)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UseRightTx indicates an expected call of UseRightTx.
func (mr *MockDurableRepoMockRecorder) UseRightTx(ctx, token, orderID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseRightTx", reflect.TypeOf((*MockDurableRepo)(nil).UseRightTx), ctx, token, orderID, now)
}

// MockCacheRepo is a mock of CacheRepo interface.
type MockCacheRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCacheRepoMockRecorder
	isgomock struct{}
}

// MockCacheRepoMockRecorder is the mock recorder for MockCacheRepo.
type MockCacheRepoMockRecorder struct {
	mock *MockCacheRepo
}

// NewMockCacheRepo creates a new mock instance.
func NewMockCacheRepo(ctrl *gomock.Controller) *MockCacheRepo {
	mock := &MockCacheRepo{ctrl: ctrl}
	mock.recorder = &MockCacheRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheRepo) EXPECT() *MockCacheRepoMockRecorder {
	return m.recorder
}

// AckExpired mocks base method.
func (m *MockCacheRepo) AckExpired(ctx context.Context, claims []models.ExpiryClaim) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AckExpired", ctx, claims)
	ret0, _ := ret[0].(error)
	return ret0
}

// AckExpired indicates an expected call of AckExpired.
func (mr *MockCacheRepoMockRecorder) AckExpired(ctx, claims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AckExpired", reflect.TypeOf((*MockCacheRepo)(nil).AckExpired), ctx, claims)
}

// AddToExpiryTimer mocks base method.
func (m *MockCacheRepo) AddToExpiryTimer(ctx context.Context, productID, userID string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToExpiryTimer", ctx, productID, userID, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToExpiryTimer indicates an expected call of AddToExpiryTimer.
func (mr *MockCacheRepoMockRecorder) AddToExpiryTimer(ctx, productID, userID, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToExpiryTimer", reflect.TypeOf((*MockCacheRepo)(nil).AddToExpiryTimer), ctx, productID, userID, expiresAt)
}

// ClaimExpired mocks base method.
func (m *MockCacheRepo) ClaimExpired(ctx context.Context, now time.Time, lease time.Duration, limit int) ([]models.ExpiryClaim, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimExpired", ctx, now, lease, limit)
	ret0, _ := ret[0].([]models.ExpiryClaim)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimExpired indicates an expected call of ClaimExpired.
func (mr *MockCacheRepoMockRecorder) ClaimExpired(ctx, now, lease, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimExpired", reflect.TypeOf((*MockCacheRepo)(nil).ClaimExpired), ctx, now, lease, limit)
}

// ClaimMembership mocks base method.
func (m *MockCacheRepo) ClaimMembership(ctx context.Context, productID, userID, ownerID string, ttl time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimMembership", ctx, productID, userID, ownerID, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimMembership indicates an expected call of ClaimMembership.
func (mr *MockCacheRepoMockRecorder) ClaimMembership(ctx, productID, userID, ownerID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimMembership", reflect.TypeOf((*MockCacheRepo)(nil).ClaimMembership), ctx, productID, userID, ownerID, ttl)
}

// CommitPurchase mocks base method.
func (m *MockCacheRepo) CommitPurchase(ctx context.Context, productID string, quantity int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitPurchase", ctx, productID, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitPurchase indicates an expected call of CommitPurchase.
func (mr *MockCacheRepoMockRecorder) CommitPurchase(ctx, productID, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitPurchase", reflect.TypeOf((*MockCacheRepo)(nil).CommitPurchase), ctx, productID, quantity)
}

// Enqueue mocks base method.
func (m *MockCacheRepo) Enqueue(ctx context.Context, productID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, productID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockCacheRepoMockRecorder) Enqueue(ctx, productID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockCacheRepo)(nil).Enqueue), ctx, productID, userID)
}

// GetFirstInQueue mocks base method.
func (m *MockCacheRepo) GetFirstInQueue(ctx context.Context, productID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstInQueue", ctx, productID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirstInQueue indicates an expected call of GetFirstInQueue.
func (mr *MockCacheRepoMockRecorder) GetFirstInQueue(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstInQueue", reflect.TypeOf((*MockCacheRepo)(nil).GetFirstInQueue), ctx, productID)
}

// GetMembership mocks base method.
func (m *MockCacheRepo) GetMembership(ctx context.Context, productID, userID string) (*models.QueueMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembership", ctx, productID, userID)
	ret0, _ := ret[0].(*models.QueueMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembership indicates an expected call of GetMembership.
func (mr *MockCacheRepoMockRecorder) GetMembership(ctx, productID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembership", reflect.TypeOf((*MockCacheRepo)(nil).GetMembership), ctx, productID, userID)
}

// GetQueueMetrics mocks base method.
func (m *MockCacheRepo) GetQueueMetrics(ctx context.Context, productID, userID string) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueueMetrics", ctx, productID, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetQueueMetrics indicates an expected call of GetQueueMetrics.
func (mr *MockCacheRepoMockRecorder) GetQueueMetrics(ctx, productID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueueMetrics", reflect.TypeOf((*MockCacheRepo)(nil).GetQueueMetrics), ctx, productID, userID)
}

// GetRight mocks base method.
func (m *MockCacheRepo) GetRight(ctx context.Context, token string) (*models.Right, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRight", ctx, token)
	ret0, _ := ret[0].(*models.Right)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRight indicates an expected call of GetRight.
func (mr *MockCacheRepoMockRecorder) GetRight(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRight", reflect.TypeOf((*MockCacheRepo)(nil).GetRight), ctx, token)
}

// GetStock mocks base method.
func (m *MockCacheRepo) GetStock(ctx context.Context, productID string) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStock", ctx, productID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetStock indicates an expected call of GetStock.
func (mr *MockCacheRepoMockRecorder) GetStock(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStock", reflect.TypeOf((*MockCacheRepo)(nil).GetStock), ctx, productID)
}

// InitStock mocks base method.
func (m *MockCacheRepo) InitStock(ctx context.Context, productID string, totalStock int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitStock", ctx, productID, totalStock)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitStock indicates an expected call of InitStock.
func (mr *MockCacheRepoMockRecorder) InitStock(ctx, productID, totalStock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitStock", reflect.TypeOf((*MockCacheRepo)(nil).InitStock), ctx, productID, totalStock)
}

// MarkPurchasedIfCurrentToken mocks base method.
func (m *MockCacheRepo) MarkPurchasedIfCurrentToken(ctx context.Context, right *models.Right, updatedAt time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPurchasedIfCurrentToken", ctx, right, updatedAt)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkPurchasedIfCurrentToken indicates an expected call of MarkPurchasedIfCurrentToken.
func (mr *MockCacheRepoMockRecorder) MarkPurchasedIfCurrentToken(ctx, right, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPurchasedIfCurrentToken", reflect.TypeOf((*MockCacheRepo)(nil).MarkPurchasedIfCurrentToken), ctx, right, updatedAt)
}

// NackExpired mocks base method.
func (m *MockCacheRepo) NackExpired(ctx context.Context, claims []models.ExpiryClaim, retryAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NackExpired", ctx, claims, retryAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// NackExpired indicates an expected call of NackExpired.
func (mr *MockCacheRepoMockRecorder) NackExpired(ctx, claims, retryAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NackExpired", reflect.TypeOf((*MockCacheRepo)(nil).NackExpired), ctx, claims, retryAt)
}

// PopAndAllocate mocks base method.
func (m *MockCacheRepo) PopAndAllocate(ctx context.Context, productID string) (string, int, int, bool, models.MembershipStatus, float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PopAndAllocate", ctx, productID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(bool)
	ret4, _ := ret[4].(models.MembershipStatus)
	ret5, _ := ret[5].(float64)
	ret6, _ := ret[6].(error)
	return ret0, ret1, ret2, ret3, ret4, ret5, ret6
}

// PopAndAllocate indicates an expected call of PopAndAllocate.
func (mr *MockCacheRepoMockRecorder) PopAndAllocate(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PopAndAllocate", reflect.TypeOf((*MockCacheRepo)(nil).PopAndAllocate), ctx, productID)
}

// PublishEvent mocks base method.
func (m *MockCacheRepo) PublishEvent(ctx context.Context, productID, userID string, payload any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishEvent", ctx, productID, userID, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishEvent indicates an expected call of PublishEvent.
func (mr *MockCacheRepoMockRecorder) PublishEvent(ctx, productID, userID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishEvent", reflect.TypeOf((*MockCacheRepo)(nil).PublishEvent), ctx, productID, userID, payload)
}

// ReclaimStaleExpired mocks base method.
func (m *MockCacheRepo) ReclaimStaleExpired(ctx context.Context, now time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReclaimStaleExpired", ctx, now)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReclaimStaleExpired indicates an expected call of ReclaimStaleExpired.
func (mr *MockCacheRepoMockRecorder) ReclaimStaleExpired(ctx, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReclaimStaleExpired", reflect.TypeOf((*MockCacheRepo)(nil).ReclaimStaleExpired), ctx, now)
}

// RefreshExpiryTimer mocks base method.
func (m *MockCacheRepo) RefreshExpiryTimer(ctx context.Context, productID, userID string, expiresAt time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshExpiryTimer", ctx, productID, userID, expiresAt)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshExpiryTimer indicates an expected call of RefreshExpiryTimer.
func (mr *MockCacheRepoMockRecorder) RefreshExpiryTimer(ctx, productID, userID, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshExpiryTimer", reflect.TypeOf((*MockCacheRepo)(nil).RefreshExpiryTimer), ctx, productID, userID, expiresAt)
}

// ReleaseMembershipClaim mocks base method.
func (m *MockCacheRepo) ReleaseMembershipClaim(ctx context.Context, productID, userID, ownerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseMembershipClaim", ctx, productID, userID, ownerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseMembershipClaim indicates an expected call of ReleaseMembershipClaim.
func (mr *MockCacheRepoMockRecorder) ReleaseMembershipClaim(ctx, productID, userID, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseMembershipClaim", reflect.TypeOf((*MockCacheRepo)(nil).ReleaseMembershipClaim), ctx, productID, userID, ownerID)
}

// RemoveFromExpiryTimer mocks base method.
func (m *MockCacheRepo) RemoveFromExpiryTimer(ctx context.Context, productID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromExpiryTimer", ctx, productID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromExpiryTimer indicates an expected call of RemoveFromExpiryTimer.
func (mr *MockCacheRepoMockRecorder) RemoveFromExpiryTimer(ctx, productID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromExpiryTimer", reflect.TypeOf((*MockCacheRepo)(nil).RemoveFromExpiryTimer), ctx, productID, userID)
}

// RemoveFromQueue mocks base method.
func (m *MockCacheRepo) RemoveFromQueue(ctx context.Context, productID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromQueue", ctx, productID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromQueue indicates an expected call of RemoveFromQueue.
func (mr *MockCacheRepoMockRecorder) RemoveFromQueue(ctx, productID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromQueue", reflect.TypeOf((*MockCacheRepo)(nil).RemoveFromQueue), ctx, productID, userID)
}

// Requeue mocks base method.
func (m *MockCacheRepo) Requeue(ctx context.Context, productID, userID string, score float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Requeue", ctx, productID, userID, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// Requeue indicates an expected call of Requeue.
func (mr *MockCacheRepoMockRecorder) Requeue(ctx, productID, userID, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Requeue", reflect.TypeOf((*MockCacheRepo)(nil).Requeue), ctx, productID, userID, score)
}

// ResetExpiryTimers mocks base method.
func (m *MockCacheRepo) ResetExpiryTimers(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetExpiryTimers", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetExpiryTimers indicates an expected call of ResetExpiryTimers.
func (mr *MockCacheRepoMockRecorder) ResetExpiryTimers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetExpiryTimers", reflect.TypeOf((*MockCacheRepo)(nil).ResetExpiryTimers), ctx)
}

// RestoreAvailableUnits mocks base method.
func (m *MockCacheRepo) RestoreAvailableUnits(ctx context.Context, productID string, quantity int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreAvailableUnits", ctx, productID, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreAvailableUnits indicates an expected call of RestoreAvailableUnits.
func (mr *MockCacheRepoMockRecorder) RestoreAvailableUnits(ctx, productID, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreAvailableUnits", reflect.TypeOf((*MockCacheRepo)(nil).RestoreAvailableUnits), ctx, productID, quantity)
}

// RestoreProductState mocks base method.
func (m *MockCacheRepo) RestoreProductState(ctx context.Context, productID string, productCount, available int, queuedUserIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreProductState", ctx, productID, productCount, available, queuedUserIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreProductState indicates an expected call of RestoreProductState.
func (mr *MockCacheRepoMockRecorder) RestoreProductState(ctx, productID, productCount, available, queuedUserIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreProductState", reflect.TypeOf((*MockCacheRepo)(nil).RestoreProductState), ctx, productID, productCount, available, queuedUserIDs)
}

// SetMembership mocks base method.
func (m *MockCacheRepo) SetMembership(ctx context.Context, membership *models.QueueMembership) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMembership", ctx, membership)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMembership indicates an expected call of SetMembership.
func (mr *MockCacheRepoMockRecorder) SetMembership(ctx, membership any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMembership", reflect.TypeOf((*MockCacheRepo)(nil).SetMembership), ctx, membership)
}

// SetRight mocks base method.
func (m *MockCacheRepo) SetRight(ctx context.Context, right *models.Right) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRight", ctx, right)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRight indicates an expected call of SetRight.
func (mr *MockCacheRepoMockRecorder) SetRight(ctx, right any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRight", reflect.TypeOf((*MockCacheRepo)(nil).SetRight), ctx, right)
}

// TryAllocate mocks base method.
func (m *MockCacheRepo) TryAllocate(ctx context.Context, productID string, quantity int) (int, int, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryAllocate", ctx, productID, quantity)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// TryAllocate indicates an expected call of TryAllocate.
func (mr *MockCacheRepoMockRecorder) TryAllocate(ctx, productID, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryAllocate", reflect.TypeOf((*MockCacheRepo)(nil).TryAllocate), ctx, productID, quantity)
}

// MockAvitoClient is a mock of AvitoClient interface.
type MockAvitoClient struct {
	ctrl     *gomock.Controller
	recorder *MockAvitoClientMockRecorder
	isgomock struct{}
}

// MockAvitoClientMockRecorder is the mock recorder for MockAvitoClient.
type MockAvitoClientMockRecorder struct {
	mock *MockAvitoClient
}

// NewMockAvitoClient creates a new mock instance.
func NewMockAvitoClient(ctrl *gomock.Controller) *MockAvitoClient {
	mock := &MockAvitoClient{ctrl: ctrl}
	mock.recorder = &MockAvitoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvitoClient) EXPECT() *MockAvitoClientMockRecorder {
	return m.recorder
}

// DecrementStock mocks base method.
func (m *MockAvitoClient) DecrementStock(ctx context.Context, idempotencyKey, productID string, quantity int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementStock", ctx, idempotencyKey, productID, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementStock indicates an expected call of DecrementStock.
func (mr *MockAvitoClientMockRecorder) DecrementStock(ctx, idempotencyKey, productID, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementStock", reflect.TypeOf((*MockAvitoClient)(nil).DecrementStock), ctx, idempotencyKey, productID, quantity)
}

// GetInitialStock mocks base method.
func (m *MockAvitoClient) GetInitialStock(ctx context.Context, productID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInitialStock", ctx, productID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInitialStock indicates an expected call of GetInitialStock.
func (mr *MockAvitoClientMockRecorder) GetInitialStock(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInitialStock", reflect.TypeOf((*MockAvitoClient)(nil).GetInitialStock), ctx, productID)
}
